name: Deploy Pixel editor

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      
      - name: Build dist
        run: npm run build
      

